#!/bin/bash
# ── Root config files ───────────────────────────────────────────
touch package.json pnpm-workspace.yaml turbo.json .env.example .gitignore .npmrc \
  README.md CONTRIBUTING.md LICENSE SECURITY.md CHANGELOG.md

# ── GitHub config ───────────────────────────────────────────────
mkdir -p .github/workflows .github/ISSUE_TEMPLATE .github/PULL_REQUEST_TEMPLATE
touch .github/workflows/ci.yml
touch .github/workflows/deploy-contracts.yml
touch .github/workflows/publish-sdk.yml
touch .github/workflows/security.yml
touch .github/ISSUE_TEMPLATE/bug_report.md
touch .github/ISSUE_TEMPLATE/feature_request.md
touch .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
touch .github/CODEOWNERS

# ── Packages: SDK (publishable npm package) ─────────────────────
mkdir -p packages/sdk/src/{core,policy,delegation,session,adapters,utils,types}
touch packages/sdk/package.json packages/sdk/tsconfig.json packages/sdk/README.md \
  packages/sdk/CHANGELOG.md packages/sdk/.eslintrc.cjs packages/sdk/vitest.config.ts \
  packages/sdk/tsup.config.ts

touch packages/sdk/src/index.ts
touch packages/sdk/src/core/AgosClient.ts
touch packages/sdk/src/core/AgentWallet.ts
touch packages/sdk/src/core/PaymentSession.ts
touch packages/sdk/src/core/x402Client.ts

touch packages/sdk/src/policy/PolicyBuilder.ts
touch packages/sdk/src/policy/PolicyEncoder.ts
touch packages/sdk/src/policy/types.ts

touch packages/sdk/src/delegation/DelegationManager.ts
touch packages/sdk/src/delegation/BudgetTree.ts

touch packages/sdk/src/session/SessionManager.ts
touch packages/sdk/src/session/SessionCache.ts

touch packages/sdk/src/adapters/langchain.ts
touch packages/sdk/src/adapters/mcp.ts
touch packages/sdk/src/adapters/crewai.ts
touch packages/sdk/src/adapters/vercelai.ts

touch packages/sdk/src/utils/eip712.ts
touch packages/sdk/src/utils/signing.ts
touch packages/sdk/src/utils/errors.ts

touch packages/sdk/src/types/index.ts
touch packages/sdk/src/types/policy.ts
touch packages/sdk/src/types/agent.ts
touch packages/sdk/src/types/payment.ts

# ── Packages: SDK Python mirror ─────────────────────────────────
mkdir -p packages/sdk-python/agos/{core,policy,delegation,adapters,utils}
touch packages/sdk-python/pyproject.toml packages/sdk-python/README.md \
  packages/sdk-python/setup.py packages/sdk-python/CHANGELOG.md
touch packages/sdk-python/agos/__init__.py
touch packages/sdk-python/agos/core/client.py
touch packages/sdk-python/agos/core/wallet.py
touch packages/sdk-python/agos/core/x402.py
touch packages/sdk-python/agos/policy/builder.py
touch packages/sdk-python/agos/delegation/manager.py
touch packages/sdk-python/agos/adapters/langchain.py
touch packages/sdk-python/agos/adapters/autogen.py
touch packages/sdk-python/agos/utils/signing.py

# ── Packages: Contracts ─────────────────────────────────────────
mkdir -p packages/contracts/{src,test,script,lib,deployments,abis}
mkdir -p packages/contracts/src/{core,governance,interfaces,libraries}
touch packages/contracts/package.json packages/contracts/foundry.toml \
  packages/contracts/README.md packages/contracts/.env.example

# Core contracts
touch packages/contracts/src/core/AgentWallet.sol
touch packages/contracts/src/core/AgentWalletFactory.sol
touch packages/contracts/src/core/PolicyEngine.sol
touch packages/contracts/src/core/DelegationRegistry.sol
touch packages/contracts/src/core/EscrowVault.sol
touch packages/contracts/src/core/AuditReceiptEmitter.sol
touch packages/contracts/src/core/PaymasterBase.sol

# Governance
touch packages/contracts/src/governance/SpendGovernor.sol
touch packages/contracts/src/governance/CircuitBreaker.sol

# Interfaces
touch packages/contracts/src/interfaces/IAgentWallet.sol
touch packages/contracts/src/interfaces/IPolicyEngine.sol
touch packages/contracts/src/interfaces/IDelegationRegistry.sol
touch packages/contracts/src/interfaces/IEscrowVault.sol
touch packages/contracts/src/interfaces/IAuditReceiptEmitter.sol

# Libraries
touch packages/contracts/src/libraries/PolicyLib.sol
touch packages/contracts/src/libraries/DelegationLib.sol
touch packages/contracts/src/libraries/X402Lib.sol

# Tests
touch packages/contracts/test/AgentWallet.t.sol
touch packages/contracts/test/PolicyEngine.t.sol
touch packages/contracts/test/DelegationRegistry.t.sol
touch packages/contracts/test/EscrowVault.t.sol
touch packages/contracts/test/AuditReceiptEmitter.t.sol
touch packages/contracts/test/CircuitBreaker.t.sol
touch packages/contracts/test/integration/FullFlow.t.sol
touch packages/contracts/test/fuzz/PolicyFuzz.t.sol
touch packages/contracts/test/invariant/PolicyInvariant.t.sol

# Deploy scripts
touch packages/contracts/script/Deploy.s.sol
touch packages/contracts/script/DeployTestnet.s.sol
touch packages/contracts/script/UpgradePolicy.s.sol
touch packages/contracts/script/VerifyContracts.s.sol

# ABIs (generated by build)
touch packages/contracts/abis/.gitkeep

# Deployments per chain
mkdir -p packages/contracts/deployments/{base-sepolia,base-mainnet,localhost}
touch packages/contracts/deployments/base-sepolia/addresses.json
touch packages/contracts/deployments/base-mainnet/addresses.json
touch packages/contracts/deployments/localhost/addresses.json

# ── Packages: Protocol (shared types/constants) ──────────────────
mkdir -p packages/protocol/src
touch packages/protocol/package.json packages/protocol/tsconfig.json
touch packages/protocol/src/index.ts
touch packages/protocol/src/constants.ts
touch packages/protocol/src/chainConfig.ts
touch packages/protocol/src/abis.ts
touch packages/protocol/src/errors.ts

# ── Apps: Facilitator (backend service) ─────────────────────────
mkdir -p apps/facilitator/src/{routes,services,middleware,db,jobs,utils,types}
touch apps/facilitator/package.json apps/facilitator/tsconfig.json \
  apps/facilitator/Dockerfile apps/facilitator/.env.example apps/facilitator/README.md

touch apps/facilitator/src/index.ts
touch apps/facilitator/src/app.ts

touch apps/facilitator/src/routes/payments.ts
touch apps/facilitator/src/routes/agents.ts
touch apps/facilitator/src/routes/policies.ts
touch apps/facilitator/src/routes/delegations.ts
touch apps/facilitator/src/routes/webhooks.ts
touch apps/facilitator/src/routes/health.ts

touch apps/facilitator/src/services/x402Verifier.ts
touch apps/facilitator/src/services/policyEnforcer.ts
touch apps/facilitator/src/services/delegationService.ts
touch apps/facilitator/src/services/auditService.ts
touch apps/facilitator/src/services/webhookService.ts
touch apps/facilitator/src/services/sessionService.ts
touch apps/facilitator/src/services/chainReader.ts

touch apps/facilitator/src/middleware/auth.ts
touch apps/facilitator/src/middleware/rateLimit.ts
touch apps/facilitator/src/middleware/circuitBreaker.ts
touch apps/facilitator/src/middleware/logger.ts

touch apps/facilitator/src/db/schema.ts
touch apps/facilitator/src/db/migrations/.gitkeep
touch apps/facilitator/src/db/client.ts
touch apps/facilitator/src/db/seed.ts

touch apps/facilitator/src/jobs/indexer.ts
touch apps/facilitator/src/jobs/webhookWorker.ts
touch apps/facilitator/src/jobs/sessionCleanup.ts

touch apps/facilitator/src/utils/crypto.ts
touch apps/facilitator/src/utils/retry.ts
touch apps/facilitator/src/utils/errors.ts
touch apps/facilitator/src/types/index.ts

# ── Apps: Indexer (standalone chain listener) ────────────────────
mkdir -p apps/indexer/src/{handlers,db,utils}
touch apps/indexer/package.json apps/indexer/tsconfig.json \
  apps/indexer/Dockerfile apps/indexer/.env.example
touch apps/indexer/src/index.ts
touch apps/indexer/src/handlers/paymentHandler.ts
touch apps/indexer/src/handlers/policyHandler.ts
touch apps/indexer/src/handlers/delegationHandler.ts
touch apps/indexer/src/db/schema.ts
touch apps/indexer/src/db/client.ts
touch apps/indexer/src/utils/blockPoller.ts

# ── Apps: Dashboard (Next.js) ────────────────────────────────────
mkdir -p apps/dashboard/src/{app,components,hooks,lib,stores,styles}
mkdir -p apps/dashboard/src/app/{dashboard,policies,agents,audit,approvals,delegation,api,\(auth\)}
touch apps/dashboard/package.json apps/dashboard/tsconfig.json \
  apps/dashboard/next.config.ts apps/dashboard/tailwind.config.ts \
  apps/dashboard/postcss.config.js apps/dashboard/.env.example \
  apps/dashboard/Dockerfile apps/dashboard/README.md

# App routes
touch apps/dashboard/src/app/layout.tsx
touch apps/dashboard/src/app/page.tsx
touch apps/dashboard/src/app/dashboard/page.tsx
touch apps/dashboard/src/app/policies/page.tsx
touch apps/dashboard/src/app/policies/new/page.tsx
touch apps/dashboard/src/app/agents/page.tsx
touch apps/dashboard/src/app/agents/\[id\]/page.tsx
touch apps/dashboard/src/app/audit/page.tsx
touch apps/dashboard/src/app/approvals/page.tsx
touch apps/dashboard/src/app/delegation/page.tsx
touch apps/dashboard/src/app/api/auth/\[...nextauth\]/route.ts
touch apps/dashboard/src/app/api/webhook/route.ts

# Components
mkdir -p apps/dashboard/src/components/{ui,agents,policies,audit,delegation,charts,layout}
touch apps/dashboard/src/components/layout/Sidebar.tsx
touch apps/dashboard/src/components/layout/Header.tsx
touch apps/dashboard/src/components/layout/ProviderTree.tsx
touch apps/dashboard/src/components/agents/AgentCard.tsx
touch apps/dashboard/src/components/agents/AgentList.tsx
touch apps/dashboard/src/components/agents/SpendMeter.tsx
touch apps/dashboard/src/components/policies/PolicyEditor.tsx
touch apps/dashboard/src/components/policies/PolicyCard.tsx
touch apps/dashboard/src/components/policies/RuleBuilder.tsx
touch apps/dashboard/src/components/audit/AuditLogTable.tsx
touch apps/dashboard/src/components/audit/ReceiptModal.tsx
touch apps/dashboard/src/components/delegation/DelegationTree.tsx
touch apps/dashboard/src/components/delegation/BudgetSliceForm.tsx
touch apps/dashboard/src/components/charts/SpendChart.tsx
touch apps/dashboard/src/components/charts/ThroughputChart.tsx

# Hooks
touch apps/dashboard/src/hooks/useAgents.ts
touch apps/dashboard/src/hooks/usePolicies.ts
touch apps/dashboard/src/hooks/useAuditLog.ts
touch apps/dashboard/src/hooks/useApprovals.ts
touch apps/dashboard/src/hooks/useRealtime.ts
touch apps/dashboard/src/hooks/useWallet.ts

# Lib
touch apps/dashboard/src/lib/api.ts
touch apps/dashboard/src/lib/wagmi.ts
touch apps/dashboard/src/lib/auth.ts
touch apps/dashboard/src/lib/utils.ts

# Stores
touch apps/dashboard/src/stores/agentStore.ts
touch apps/dashboard/src/stores/notificationStore.ts

# ── Apps: Docs site ──────────────────────────────────────────────
mkdir -p apps/docs/docs/{sdk,contracts,api,guides,concepts}
touch apps/docs/package.json apps/docs/docusaurus.config.ts \
  apps/docs/sidebars.ts apps/docs/README.md
touch apps/docs/docs/intro.md
touch apps/docs/docs/guides/quickstart.md
touch apps/docs/docs/guides/first-agent.md
touch apps/docs/docs/guides/policy-guide.md
touch apps/docs/docs/guides/delegation.md
touch apps/docs/docs/guides/oversight.md
touch apps/docs/docs/concepts/architecture.md
touch apps/docs/docs/concepts/x402.md
touch apps/docs/docs/concepts/policy-dsl.md
touch apps/docs/docs/sdk/installation.md
touch apps/docs/docs/sdk/api-reference.md
touch apps/docs/docs/contracts/overview.md
touch apps/docs/docs/api/endpoints.md

# ── Apps: Example agents ────────────────────────────────────────
mkdir -p apps/examples/{basic-agent,multi-agent,langchain-agent,mcp-agent}
touch apps/examples/basic-agent/package.json apps/examples/basic-agent/index.ts \
  apps/examples/basic-agent/README.md
touch apps/examples/multi-agent/package.json apps/examples/multi-agent/index.ts \
  apps/examples/multi-agent/README.md
touch apps/examples/langchain-agent/package.json apps/examples/langchain-agent/index.ts \
  apps/examples/langchain-agent/README.md
touch apps/examples/mcp-agent/package.json apps/examples/mcp-agent/index.ts \
  apps/examples/mcp-agent/README.md

# ── Infra / DevOps ───────────────────────────────────────────────
mkdir -p infra/{docker,k8s,terraform/{modules,environments}}
touch infra/docker/docker-compose.yml
touch infra/docker/docker-compose.dev.yml
touch infra/docker/docker-compose.test.yml
touch infra/k8s/facilitator-deployment.yaml
touch infra/k8s/indexer-deployment.yaml
touch infra/k8s/dashboard-deployment.yaml
touch infra/k8s/ingress.yaml
touch infra/k8s/secrets.yaml
touch infra/terraform/modules/base/main.tf
touch infra/terraform/environments/staging/main.tf
touch infra/terraform/environments/production/main.tf

# ── Shared config ────────────────────────────────────────────────
mkdir -p config
touch config/eslint.base.cjs config/tsconfig.base.json \
  config/vitest.base.ts config/prettier.config.cjs

# ── Scripts ──────────────────────────────────────────────────────
mkdir -p scripts
touch scripts/setup.sh scripts/deploy-testnet.sh scripts/gen-abis.sh \
  scripts/publish.sh scripts/verify-contracts.sh

echo "ALL DONE"
